server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db200420_guli_edu?serverTimezone=GMT%2B8
    username: root
    password: system
  jackson:  #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #mybatis-plus:
  mapper-locations: classpath:com/guli/service/edu/mapper/xml/*.xml


## 设置日志级别
#logging:
#  level:
#    root: ERROR

ribbon:
  MaxAutoRetries: 2 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1 （集群状态下）