server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyId: LTAI4GKTeBQ4GoFieSmu3pPk
    keySecret: bdvRu5HDDTGJKHGhk3x1JJyBHt4RT8
    templateGroupId: e355be8e657b3f0fc01c850c91c511ac #转码模板组id
    workflowId: 8846a6e3c65885d699fcd785ff2dfedb #工作流id